- name: Kubeadm reset
  shell: kubeadm reset -f
  args:
    chdir: $HOME

- name: Join node to cluster
  shell: "{{ hostvars[groups['masters'][0]]['join_command'] }}"
  ignore_errors: yes
  args:
    chdir: $HOME