- name: Create file repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Disable SELinux
  ansible.builtin.selinux:
    state: disabled

- name: Install Packages kubernetes
  yum:
    name: "{{ item }}"
    disable_excludes: kubernetes
  loop: "{{ k8s_packages }}"

- name: forçar os ajustes no systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: yes